mainproject/account/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

app_name = "account"
urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name='logout'),
]

mainproject/mainproject/urls.py
from django.contrib import admin
from django.urls import path, include

import mainapp.views
import account.views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',mainapp.views.home, name="home"),

    path('account/', include('account.urls')),
    path('write/', include ('write.urls')),
]

mainproject/user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'user'

urlpatterns = [
    path('join/', views.UserRegister.as_view(), name="join"),
    path('login/', views.UserLogin.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

mainproject/write/urls.py
from django.urls import path
from .views import BoardDetail, BoardIndex, BoardSearchlist
from . import views
import write.views

app_name = "write"
urlpatterns = [

    path("detail/",BoardDetail.as_view(), name='detail'),
    path("create/",write.views.create, name='create'),
    path('index/',BoardIndex.as_view(), name='index'),
    path('searchlist/',write.views.searchlist, name='searchlist')
]

mainproject/write/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

from django.contrib.contenttypes.fields import GenericRelation
from hitcount.models import HitCount, HitCountMixin

# 계정 테이블 - 사용안함
class Account(models.Model):
    id = models.CharField(max_length=20, primary_key=True)
    password = models.CharField(max_length=30)
    email = models.EmailField(unique=True, null=False)

    def __str__(self):
        return self.id

# 과목 영역 테이블
class Subject_range(models.Model):
    # 영역(PK)
    subject_range = models.CharField(primary_key=True, max_length=50)
    
    def __str__(self):
        return self.subject_range

# 과목 정보 테이블 - 사용안함
class Subject_code(models.Model):
    # 과목 코드(PK)
    subject_code = models.CharField(max_length=20, primary_key=True)
    # 과목명
    subject_name = models.CharField(max_length=20)

    def __str__(self):
        return self.subject_code + '    ' + self.subject_name

# 과목 & 강사 테이블
class Subject(models.Model):
    # PK를 따로 설정하지 않았습니다.
    # PK는 장고에서 인덱스 형식으로 자동 생성해줍니다. ex) 1,2,3,4,5... 
    # PK는 id라는 컬럼명으로 저장되어 있습니다.

    # 영역 (FK) - 과목 영역 테이블에서 가져옴
    subject_range = models.ForeignKey(Subject_range, on_delete = models.CASCADE, null=True)
    
    # # 과목 코드 (FK) - 과목 정보 테이블에서 가져옴
    # subject_code = models.ForeignKey(Subject_code, on_delete=models.CASCADE)

    # 과목명
    subject_name = models.CharField(max_length=50, null=True)

    # 강사명
    professor = models.CharField(max_length=50)
    # 추천
    recommendation = models.IntegerField(default=0)
    # 비추천
    nonrecommendation = models.IntegerField(default=0)
    
    # 과제 - 많음 보통 없음 과제베스트
    homework_large = models.IntegerField(default=0)
    homework_medium = models.IntegerField(default=0)
    homework_small = models.IntegerField(default=0)
    homework_best = models.CharField(max_length=20, null=True)

    # 팀플 - 있음 없음 팀플베스트
    team_yes = models.IntegerField(default=0)
    team_no = models.IntegerField(default=0)
    team_best = models.CharField(max_length=20, null=True)

    # 학점비율 - 잘줌 깐깐함 F주의 학점비율베스트
    grade_good = models.IntegerField(default=0)
    grade_bad = models.IntegerField(default=0)
    grade_f = models.IntegerField(default=0)
    grade_best = models.CharField(max_length=20, null=True)

    # 출결 - 호명 전자출결 안함 출결베스트
    attendance_speak = models.IntegerField(default=0)
    attendance_elec = models.IntegerField(default=0)
    attendance_none = models.IntegerField(default=0)
    attendance_best = models.CharField(max_length=20, null=True)

    # 시험횟수 - 3번이상 두번 한번 없음 시험횟수베스트
    test_3 = models.IntegerField(default=0)
    test_2 = models.IntegerField(default=0)
    test_1 = models.IntegerField(default=0)
    test_0 = models.IntegerField(default=0)
    test_best = models.CharField(max_length=20, null=True)

    def __str__(self):
        return str(self.id) + ' ' + str(self.subject_range) + ' ' + str(self.subject_name) + ' ' + str(self.professor)

# 강의 평가 테이블
class Evaluation(models.Model):
    # PK를 따로 설정하지 않았습니다.
    # PK는 장고에서 인덱스 형식으로 자동 생성해줍니다. ex) 1,2,3,4,5... 
    # PK는 id라는 컬럼명으로 저장되어 있습니다.
    
    # 강의평가 작성자 ID
    writer_id = models.CharField(max_length=20)
    # 평가내용
    evaluation_text = models.TextField(max_length=2000)
    # 작성날짜
    pub_date = models.DateTimeField('date published')
    # 과목 테이블에서 어떤 강사와 어떤 과목을 선택했는지 알려주는 컬럼
    subject_id = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id) + ' ' + self.writer_id


#글 관련 항목
class Write_index(models.Model):
    homework = models.CharField(max_length=20)
    team = models.CharField(max_length=20)
    grade = models.CharField(max_length=20)
    attendance = models.CharField(max_length=20)
    test = models.CharField(max_length=20)
    hit_count_generic = GenericRelation( HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')

    def __str__(self):
        return self.text

mainproject/mainapp/views.py
from django.shortcuts import render,redirect
from .models import Subject_range,Subject_code,Subject

# Create your views here.
def index(request):
    return render(request, 'index.html')

def searchlist(request):
    searchtext=request.GET.get('searchtext','')
    subject=Subject.objects.all()

    if not searchtext == '':
        subject=subject.filter(subject_name=searchtext)
        # subjectrange=subject.filter(subject_range=searchtext)
        # if not subject == '':
        #     return render(request, 'searchlist.html', {'subject':subject, 'searchtext':searchtext})
        # elif not subjectrange =='':
        #     return render(request, 'searchlist.html', {'subjectrange':subjectrange})
        # # else:
        #     return redirect('index')
        return render(request, 'searchlist.html', {'subject':subject, 'searchtext':searchtext})
    else:
        return redirect('index')

mainproject/write/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages

from django.views.generic.base import View
from django.http import HttpResponseForbidden
from urllib.parse import urlparse

from django.views.generic.list import ListView


from django.contrib.auth.models import User

from django.core.paginator import Paginator

from .models import Account
from .models import Subject_range
from .models import Subject_code    
from .models import Subject    
from .models import Evaluation
from .models import Write_index
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from hitcount.views import HitCountDetailView


#class형 뷰의 generic view를 이용하여 구현

class BoardIndex(ListView):
    model = Subject
    template_name = 'write/index.html'

class BoardSearchlist(ListView):
    model = Subject
    template_name = 'write/searchlist.html'
    subject=Subject.objects.all()

def searchlist(request):
    searchtext=request.GET.get('searchtext','')
    subject=Subject.objects.all()

    if not searchtext == '':
        subject=subject.filter(subject_name__icontains=searchtext)
        return render(request, 'write/searchlist.html', {'subject':subject, 'searchtext':searchtext})
    else:
        return redirect('write/index')

class BoardDetail(ListView):
    model = Subject
    template_name = 'write/detail.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        global page
        context = super(BoardDetail, self).get_context_data(**kwargs)
        paginator = context['paginator']

        #5개씩 잘라서 보여줌
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        return context


# class BoardCreate(CreateView) : 
#     model = Subject, Evaluation
#     fields = ['writer_id', 'evaluation_text' , 'homework_large','homework_medium','homework_small',' homework_best','team_yes','team_no','team_best','grade_good','grade_bad','grade_f',' grade_best','attendance_speak','attendance_elec','attendance_none','attendance_best','test_3','test_2','test_1','test_0','test_best',]
#     template_name_suffix = '_create'
#     success_url ='/write/detail/'

    
#     로그인한 사람 글쓰기 가능
#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         form.instance.autor_id = self.request.user.id
#         if form.is_valid() :
#             form.instance.save()
#             return redirect('/write')
#         else : 
#             return self.render_to_response({'form' : form})
        
        
def create(request):
    return render(request, 'write/create.html')

mainproject/mainapp/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>base</title>
<link rel="stylesheet" href="../../static/css/home.css">
<link rel="stylesheet" href="../../static/css/base.css">
</head>
<body>
<div class="frame" style="height: 850px;">       
  <div class="header">
    <h2>대학강의평가 멋사</h2>
  </div>        
<div class="nav">
      <!-- 로그인o -->
      {% if user.is_authenticated %}
      <pre><a href="">{{user.username}}</a>   <a href="javascript:{document.getElementById('logout').submit()}">Logout</a></pre>
      <form id="logout" method="POST" action="{% url 'account:logout' %}">
          {% csrf_token %} <input type="hidden" />
      </form>
      <!-- 로그인x-->
      {% else %}
      <pre><a href="{% url 'account:login' %}">로그인</a>    <a href="{% url 'account:signup' %}">회원가입</a></pre>
      {%endif%}
    </div>
  <div class="content">
    {% block content %}
    {% endblock %}
    <div class="myaccount">
      <img src="../../static/img/likelion.png" width="300px" class ="center">
      <h2>chosun</h2>
      <br>
      <a href="{% url 'write:index' %}">write</a>
    </div>
  </div> 

<div class="container">

  <div class="logo"><img src="../../static/img/logo.jpg" width="120px"> </div>
  <div class="footer" >조선대학교 멋쟁이 사자처럼 김창우 김미영 마서연 한지원 윤지유</div>
</div>
</div>
</body>
</html>

mainproject/mainapp/templates/index.html
{% extends 'base.html'%}

{%block first%}
    <div class="content">
    <center><div class="indexbody">
    <form method="GET" action="{% url 'searchlist' %}">
        <div class="search_bar" style="width : 800px">
        <div class="input-group mb-3">
            <input type="text" name="searchtext" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="button-addon2">
            <!-- <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="button-addon2">검색</button>
            </div> -->
        </div>
        </div>
    </form>
    <!-- <h5>수강과목 검색</h5>
        <script>
            function categoryChange(f) {
                var cat_a = ['중핵', '사고와표현1,2보고서작성및발표', '대학영어ESL1', '생활영어1,2ESL2', '자기계발과사회봉사', '고전및외국어'];
                var cat_b = ['인성과논리', '문학과예술', '역사와사회', '자연과과학'];
                var cat_c = ['인문학과예술체육', '사회과학과국제문화', '정보화와과학기술', '취업과창업'];
                var cat_d = ['기초인문사회', '기초자연과학'];
                var target = document.getElementById("second");
            
                if(f.value == "a") var e = cat_a;
                else if(f.value == "b") var e = cat_b;
                else if(f.value == "c") var e = cat_c;
                else if(f.value == "d") var e = cat_d
            
                target.options.length = 0;
            
                for (x in e) {
                    var opt = document.createElement("option");
                    opt.value = e[x];
                    opt.innerHTML = e[x];
                    target.appendChild(opt);
                }
            }

            function submit(){
                var range = document.getElementById("second");
                var rangeText = range.options[range.selectedIndex].text;
            }
            
        </script>
        <form method="GET" action="{% url 'searchlist' %}">
            <select class="selectbox" id="first" onchange="categoryChange(this)">
                <option>선택해주세요</option>
                <option value="a">기초교양</option>
                <option value="b">심화교양</option>
                <option value="c">일반교양</option>
                <option value="d">기초교육</option>
            </select>        
            <select class="selectbox" id="second" onchange="submit(this)" >
                <option value="range">선택해주세요</option>
            </select>
            <input class="btn btn-primary" type="submit" value="검색"></input>
        </form> -->
<!-- ================================================================================================================ -->
    <h5 styel="text-align:left">최근 강의평</h5>
    <div class="card" style="width: 800px;">
        <div class="card-body">
            <h5 class="card-title" style="text-align: left;">강의명</h5>
            <p class="card-text" style="text-align: left;">에벱베ㅔ베베베강의평가내용어쩌고저쩌고</p>
            <a href="#" class="btn btn-primary">자세히보기</a>
        </div>
    </div>
    <br>
    <br>
    <div class="card" style="width: 800px;">
        <div class="card-body">
            <h5 class="card-title" style="text-align: left;">강의명</h5>
            <p class="card-text" style="text-align: left;">에벱베ㅔ베베베강의평가내용어쩌고저쩌고</p>
            <a href="#" class="btn btn-primary">자세히보기</a>
        </div>
    </div>
    <br>
    <br>
    <div class="card" style="width: 800px;">
        <div class="card-body">
            <h5 class="card-title" style="text-align: left;">강의명</h5>
            <p class="card-text" style="text-align: left;">에벱베ㅔ베베베강의평가내용어쩌고저쩌고</p>
            <a href="#" class="btn btn-primary">자세히보기</a>
        </div>
    </div>


{%endblock%}

mainproject/mainapp/templates/searchlist.html
{% extends 'base.html'%}

{%block first%}  
    <!--각자 페이지 마다 콘텐츠 들어갈 부분-->
  <div class="content">
    <h2>{{searchtext}}</h2>
    <br>
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">과목명</th>
            <th scope="col">교수명</th>
            <th scope="col">추천수</th>
          </tr>
        </thead>
        <tbody>
          <!-- {%if not subject == ''%} -->
            {% for subjects in subject.all %}
              <tr>
                <td>{{subjects.subject_name}}</td>
                <td><a href="{%url 'index'%}" style="color:black">{{subjects.professor}}</a></td>
                <td>@mdo</td>
              </tr>
            {% endfor %}
          <!-- {% endif %}

          {%if not subjectrange == ''%}
            {% for subjects in subjectrange.all %}
              <tr>
                <td>{{subjects.subject_name}}</td>
                <td><a href="{%url 'index'%}" style="color:black">{{subjects.professor}}</a></td>
                <td>@mdo</td>
              </tr>
            {% endfor %}
          {% endif %} -->


        </tbody>
        <br>
      </table>

<!--각자 페이지 마다 콘텐츠 들어갈 부분 끝-->
{%endblock%}

mainproject/mainapp/templates/write.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>base</title>
<link rel="stylesheet" href="../../static/css/base.css">
<link rel="stylesheet" href="../../static/css/write.css">
</head>

<body>
<div class="frame">       
  <div class="header">
    <h2>대학강의평가 멋사</h2>
    <pre><a href="">login</a>   <a href="">signup</a>   <a href="">index</a>   <a href="">detail</a>   <a href="">write</a></pre>
   
  </div>        
  <div class = "menu">
    <img src="../../static/img/back.jpg" width="40px">
  </div>
    <!--각자 페이지 마다 콘텐츠 들어갈 부분-->

  <div class="content">
    
    <div class = "title">
        <h1>새 강의평 쓰기</h1>
    </div>

    <div class = "line"> </div>

    
    <div class = "choice">
      <h3>과제</h3>
      <input type="radio" name="group1" value="1" /> 많음 
      <input type="radio" name="group1" value="2" /> 보통
      <input type="radio" name="group1" value="3" /> 없음

      <h3>팀플</h3>
      <input type="radio" name="group2" value="1" /> 있음 
      <input type="radio" name="group2" value="2" /> 없음
      
      <h3>학점비율</h3>
      <input type="radio" name="group3" value="1" /> 잘줌 
      <input type="radio" name="group3" value="2" /> 깐깐함
      <input type="radio" name="group3" value="3" /> F주의

      <h3>출결</h3>
      <input type="radio" name="group4" value="1" />호명
      <input type="radio" name="group4" value="2" /> 전자출결
      <input type="radio" name="group4" value="3" /> 안함

      <h3>시험횟수</h3>
      <input type="radio" name="group5" value="1" />3번이상
      <input type="radio" name="group5" value="2" /> 두번
      <input type="radio" name="group5" value="3" /> 한번
      <input type="radio" name="group5" value="4" /> 없음
    
    </div>
    
    <div class = "line"> </div>

    <div class = "good">
        <h3>추천</h3>
        
        
        <pre><img class="like" src="../../static/img/like.jpg" width="40px" >     <img class="unlike" src="../../static/img/unlike.jpg" width="40px"></pre>


    </div>

    <div class = "line"> </div>

    <div class = "year">
      <label for="year">수강학기</label>
      <br>
      <br>
      <select id="year">
        <option value="20192">2019-2학기</option>
        <option value="20191">2019-1학기</option>
        <option value="20182">2018-2학기</option>

      </select>

    </div>

    <div class = "line"> </div>

    <div class = "text">
        <pre>네모칸씨에스에스 한거 안에 글자제한 500자로 텍스트 작성하게하기</pre>
    </div>

    <div class = "upload">
        <form>
            <input type = "button" value = "제출하기" />
        </form>
    </div>
  </div> 
<!--각자 페이지 마다 콘텐츠 들어갈 부분 끝-->
<div class="container">