mainproject/mainproject/urls.py
from django.contrib import admin
from django.urls import path, include

import mainapp.views
import account.views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',mainapp.views.home, name="home"),

    path('account/', include('account.urls')),
    path('write/', include ('write.urls')),
]

mainproject/user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'user'

urlpatterns = [
    path('join/', views.UserRegister.as_view(), name="join"),
    path('login/', views.UserLogin.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

mainproject/write/urls.py
from django.urls import path
from .views import BoardDetail, BoardIndex, BoardSearchlist
from . import views
import write.views

app_name = "write"
urlpatterns = [

    path("detail/",BoardDetail.as_view(), name='detail'),
    path("create/",write.views.create, name='create'),
    path('index/',BoardIndex.as_view(), name='index'),
    path('searchlist/',write.views.searchlist, name='searchlist')
]

mainproject/write/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

from django.contrib.contenttypes.fields import GenericRelation
from hitcount.models import HitCount, HitCountMixin

# 계정 테이블 - 사용안함
class Account(models.Model):
    id = models.CharField(max_length=20, primary_key=True)
    password = models.CharField(max_length=30)
    email = models.EmailField(unique=True, null=False)

    def __str__(self):
        return self.id

# 과목 영역 테이블
class Subject_range(models.Model):
    # 영역(PK)
    subject_range = models.CharField(primary_key=True, max_length=50)
    
    def __str__(self):
        return self.subject_range

# 과목 정보 테이블 - 사용안함
class Subject_code(models.Model):
    # 과목 코드(PK)
    subject_code = models.CharField(max_length=20, primary_key=True)
    # 과목명
    subject_name = models.CharField(max_length=20)

    def __str__(self):
        return self.subject_code + '    ' + self.subject_name

# 과목 & 강사 테이블
class Subject(models.Model):
    # PK를 따로 설정하지 않았습니다.
    # PK는 장고에서 인덱스 형식으로 자동 생성해줍니다. ex) 1,2,3,4,5... 
    # PK는 id라는 컬럼명으로 저장되어 있습니다.

    # 영역 (FK) - 과목 영역 테이블에서 가져옴
    subject_range = models.ForeignKey(Subject_range, on_delete = models.CASCADE, null=True)
    
    # # 과목 코드 (FK) - 과목 정보 테이블에서 가져옴
    # subject_code = models.ForeignKey(Subject_code, on_delete=models.CASCADE)

    # 과목명
    subject_name = models.CharField(max_length=50, null=True)

    # 강사명
    professor = models.CharField(max_length=50)
    # 추천
    recommendation = models.IntegerField(default=0)
    # 비추천
    nonrecommendation = models.IntegerField(default=0)
    
    # 과제 - 많음 보통 없음 과제베스트
    homework_large = models.IntegerField(default=0)
    homework_medium = models.IntegerField(default=0)
    homework_small = models.IntegerField(default=0)
    homework_best = models.CharField(max_length=20, null=True)

    # 팀플 - 있음 없음 팀플베스트
    team_yes = models.IntegerField(default=0)
    team_no = models.IntegerField(default=0)
    team_best = models.CharField(max_length=20, null=True)

    # 학점비율 - 잘줌 깐깐함 F주의 학점비율베스트
    grade_good = models.IntegerField(default=0)
    grade_bad = models.IntegerField(default=0)
    grade_f = models.IntegerField(default=0)
    grade_best = models.CharField(max_length=20, null=True)

    # 출결 - 호명 전자출결 안함 출결베스트
    attendance_speak = models.IntegerField(default=0)
    attendance_elec = models.IntegerField(default=0)
    attendance_none = models.IntegerField(default=0)
    attendance_best = models.CharField(max_length=20, null=True)

    # 시험횟수 - 3번이상 두번 한번 없음 시험횟수베스트
    test_3 = models.IntegerField(default=0)
    test_2 = models.IntegerField(default=0)
    test_1 = models.IntegerField(default=0)
    test_0 = models.IntegerField(default=0)
    test_best = models.CharField(max_length=20, null=True)

    def __str__(self):
        return str(self.id) + ' ' + str(self.subject_range) + ' ' + str(self.subject_name) + ' ' + str(self.professor)

# 강의 평가 테이블
class Evaluation(models.Model):
    # PK를 따로 설정하지 않았습니다.
    # PK는 장고에서 인덱스 형식으로 자동 생성해줍니다. ex) 1,2,3,4,5... 
    # PK는 id라는 컬럼명으로 저장되어 있습니다.
    
    # 강의평가 작성자 ID
    writer_id = models.CharField(max_length=20)
    # 평가내용
    evaluation_text = models.TextField(max_length=2000)
    # 작성날짜
    pub_date = models.DateTimeField('date published')
    # 과목 테이블에서 어떤 강사와 어떤 과목을 선택했는지 알려주는 컬럼
    subject_id = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id) + ' ' + self.writer_id


#글 관련 항목
class Write_index(models.Model):
    homework = models.CharField(max_length=20)
    team = models.CharField(max_length=20)
    grade = models.CharField(max_length=20)
    attendance = models.CharField(max_length=20)
    test = models.CharField(max_length=20)
    hit_count_generic = GenericRelation( HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')

    def __str__(self):
        return self.text

mainproject/write/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages

from django.views.generic.base import View
from django.http import HttpResponseForbidden
from urllib.parse import urlparse

from django.views.generic.list import ListView


from django.contrib.auth.models import User

from django.core.paginator import Paginator

from .models import Account
from .models import Subject_range
from .models import Subject_code    
from .models import Subject    
from .models import Evaluation
from .models import Write_index
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from hitcount.views import HitCountDetailView


#class형 뷰의 generic view를 이용하여 구현

class BoardIndex(ListView):
    model = Subject
    template_name = 'write/index.html'

class BoardSearchlist(ListView):
    model = Subject
    template_name = 'write/searchlist.html'
    subject=Subject.objects.all()

def searchlist(request):
    searchtext=request.GET.get('searchtext','')
    subject=Subject.objects.all()

    if not searchtext == '':
        subject=subject.filter(subject_name__icontains=searchtext)
        return render(request, 'write/searchlist.html', {'subject':subject, 'searchtext':searchtext})
    else:
        return redirect('write/index')

class BoardDetail(ListView):
    model = Subject
    template_name = 'write/detail.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        global page
        context = super(BoardDetail, self).get_context_data(**kwargs)
        paginator = context['paginator']

        #5개씩 잘라서 보여줌
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        return context


# class BoardCreate(CreateView) : 
#     model = Subject, Evaluation
#     fields = ['writer_id', 'evaluation_text' , 'homework_large','homework_medium','homework_small',' homework_best','team_yes','team_no','team_best','grade_good','grade_bad','grade_f',' grade_best','attendance_speak','attendance_elec','attendance_none','attendance_best','test_3','test_2','test_1','test_0','test_best',]
#     template_name_suffix = '_create'
#     success_url ='/write/detail/'

    
#     로그인한 사람 글쓰기 가능
#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         form.instance.autor_id = self.request.user.id
#         if form.is_valid() :
#             form.instance.save()
#             return redirect('/write')
#         else : 
#             return self.render_to_response({'form' : form})
        
        
def create(request):
    return render(request, 'write/create.html')

mainproject/templates/write/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>조선대학교강의평가</title>
    
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
        .selectbox{
            width: 350px;
        }
    </style>
</head>
<body>
<div class="frame">       
    <div class="header">
        <h2>대학강의평가 멋사</h2>
    </div>

{% block content %}
{% endblock %}

    <div class="container">
       <div class="logo"><img src="{% static 'img/logo.jpg' %}" width="120px"> </div>
       <div class="footer" >조선대학교 멋쟁이 사자처럼 김창우 장미영 마서연 한지원 윤지유</div>
    </div>


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

mainproject/templates/write/create.html
{% extends 'write/base.html'%}
{% load static %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
    <title>detail</title>

</head>

<div class="content">

    <div class = "title">
        <h1>새 강의평 쓰기</h1>
    </div>

    <div class = "line"> </div>

    <div class = "upload">

    <div class = "choice">
    <h3>과제</h3>
    <input type="radio" name="group1" value="1" /> 많음 
    <input type="radio" name="group1" value="2" /> 보통
    <input type="radio" name="group1" value="3" /> 없음

    <h3>팀플</h3>
    <input type="radio" name="group2" value="1" /> 있음 
    <input type="radio" name="group2" value="2" /> 없음

    <h3>학점비율</h3>
    <input type="radio" name="group3" value="1" /> 잘줌 
    <input type="radio" name="group3" value="2" /> 깐깐함
    <input type="radio" name="group3" value="3" /> F주의

    <h3>출결</h3>
    <input type="radio" name="group4" value="1" />호명
    <input type="radio" name="group4" value="2" /> 전자출결
    <input type="radio" name="group4" value="3" /> 안함

    <h3>시험횟수</h3>
    <input type="radio" name="group5" value="1" />3번이상
    <input type="radio" name="group5" value="2" /> 두번
    <input type="radio" name="group5" value="3" /> 한번
    <input type="radio" name="group5" value="4" /> 없음

    </div>

    <div class = "line"> </div>

    <div class = "good">
        <h3>추천</h3>
        
        
        <pre><img class="like" src="{% static 'img/like.jpg'%}" width="40px" >     <img class="unlike" src="{% static 'img/unlike.jpg'%}" width="40px"></pre>


    </div>

    <div class = "line"> </div>

    <div class = "year">
    <label for="year">수강학기</label>
    <br>
    <br>
    <select id="year">
    <option value="20192">2019-2학기</option>
    <option value="20191">2019-1학기</option>
    <option value="20182">2018-2학기</option>

    </select>

    </div>

    <div class = "line"> </div>

    <div class = "text">
        <pre>  수강후기를 남기세요.</pre>
    </div>


    <input type = "submit" value = "제출하기" />
    </div>
</div>
{%endblock%}

mainproject/templates/write/delete.html
{% extends 'write/base.html'%}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/delete.css' %}">
    <title>Board</title>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>

</head>


{% block content %}
<form class="delete_comment" action="" method="post">
    {% csrf_token%}
    <h3>이 게시물을 삭제하겠습니까?</h3>
    <div class="btn">
        <input type="submit" value="삭제">
        <input type="button" value="취소" onclick="goBack();">
    </div>
</form>

{% endblock %}

mainproject/templates/write/detail.html
{% extends 'write/base.html'%}
{% load static %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
    <title>detail</title>

</head>



    <div class="wrapper">
        <div class="item info">
            <div class="info-context">검색한 과목명</div>
            <div class="info-context">교수명</div>
            <div class="info-context">마서연</div>
        </div>
    

        <!-- 평가들을 합산한 결과 -->
        <div class="item fb-sum">
            <div class="fb-sum-context">강의평</div>
            <div class="fb-sum-context"><a href="{% url 'write:create' %}">새 강의평 쓰기</a></div>

            <div class="fb-sum-context">좋아요</div>
            <div class="fb-sum-context">싫어요</div>
            <div class="fb-sum-context">과제</div>
            <div class="fb-sum-context">보통</div>
            <div class="fb-sum-context">조모임</div>
            <div class="fb-sum-context">없음</div>
            <div class="fb-sum-context">학점비율</div>
            <div class="fb-sum-context">비율 채워줌</div>
            <div class="fb-sum-context">출결</div>
            <div class="fb-sum-context">직접호명</div>
            <div class="fb-sum-context">시험횟수</div>
            <div class="fb-sum-context">2번</div>
        </div>

      <!-- 강의평 감싸는 박스 -->
        <div class="item feedback">
    <!-- <p>강의평 감싸는 박스</p> -->
            <div class="feedback-context">익명</div>
            <!-- <div class="feedback-context"><p style="text-align: right;">추천</p></div> -->
            <div class="feedback-context"><p style="text-align: right;">삭제</p></div>
            <div class="feedback-context">19년도 2학기 수강자</div>
            <div class="feedback-context">교수님 진짜 성격도 좋고 다 좋습니다.</div>
        </div>

        <div class="item feedback">
            <!-- <p>강의평 감싸는 박스</p> -->
            <div class="feedback-context">익명</div>
            <!-- <div class="feedback-context"><p style="text-align: right;">추천</p></div> -->
            <div class="feedback-context"><p style="text-align: right;">삭제</p></div>
            <div class="feedback-context">19년도 2학기 수강자</div>
            <div class="feedback-context">그냥 들으세요 믿듣</div>
        </div>
        
        <div class="item feedback">
        <!-- <p>강의평 감싸는 박스</p> -->
            <div class="feedback-context">악명</div>
            <!-- <div class="feedback-context"><p style="text-align: right;">추천</p></div> -->
            <div class="feedback-context"><p style="text-align: right;">삭제</p></div>
            <div class="feedback-context">19년도 2학기 수강자</div>
            <div class="feedback-context">꿀강</div>
        </div>
    </div>          
  
{% endblock %}



<!-- 쿼리셋 메소드들
.all() lec클래스에서 만든 모든 객체(쿼리셋)를 가져오는 메소드 -->
<!-- .count() 객체 개수 반환 
.first() 첫번째 객체 반환
.last() 마지막 객체 반환 -->

mainproject/templates/write/index.html
{% extends 'write/base.html'%}
{% load static %}

{% block content %}

<div class="content">
    <center><div class="indexbody">
    <form method="GET" action="{% url 'write:searchlist' %}">
        <div class="search_bar" style="width : 800px">
        <div class="input-group mb-3">
            <input type="text" name="searchtext" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="button-addon2">
        </div>
        </div>
    </form>
    <a href="{% url 'write:detail' %}">detail</a>
<!-- ================================================================================================================ -->
    <h5 styel="text-align:left">최근 강의평</h5>
    <div class="card" style="width: 800px;">
        <div class="card-body">
            <h5 class="card-title" style="text-align: left;">강의명</h5>
            <p class="card-text" style="text-align: left;">에벱베ㅔ베베베강의평가내용어쩌고저쩌고</p>
            <a href="#" class="btn btn-primary">자세히보기</a>
        </div>
    </div>
    <br>
    <br>
    
    <br>
    <!-- {% for object in object_list %}
    <div class="card" style="width: 800px;">
        <div class="card-body">
            <h5 class="card-title" style="text-align: left;">{{object.}}</h5>
            <p class="card-text" style="text-align: left;">에벱베ㅔ베베베강의평가내용어쩌고저쩌고</p>
            <a href="#" class="btn btn-primary">자세히보기</a>
        </div>
    </div>
    {%endfor%} -->



{%endblock%}

mainproject/templates/write/searchlist.html
{% extends 'write/base.html'%}
{% load static %}

{% block content %}
    <!--각자 페이지 마다 콘텐츠 들어갈 부분-->
  <div class="content">
    <h2>{{searchtext}}</h2>
    <br>
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">과목명</th>
            <th scope="col">교수명</th>
            <th scope="col">추천수</th>
          </tr>
        </thead>
        <tbody>
            {% for subjects in subject.all %}
              <tr>
                <td>{{subjects.subject_name}}</td>
                <td><a href="{%url 'write:detail'%}" style="color:black">{{subjects.professor}}</a></td>
                <td>@mdo</td>
              </tr>
            {% endfor %}
        </tbody>
        <br>
      </table>

<!--각자 페이지 마다 콘텐츠 들어갈 부분 끝-->
{%endblock%}

mainproject/templates/write/write.html
{% extends 'base.html' %}<!-- base,html을 불러오는 코드 -->
{% load static %}



{% block contents %}

<div class="content">

<div class = "title">
    <h1>새 강의평 쓰기</h1>
</div>

<div class = "line"> </div>

<div class = "upload">
<form action="{% url 'fb_create' %}" method="post">
    {% csrf_token %}
<div class = "choice">
<h3>과제</h3>
<input type="radio" name="group1" value="1" /> 많음 
<input type="radio" name="group1" value="2" /> 보통
<input type="radio" name="group1" value="3" /> 없음

<h3>팀플</h3>
<input type="radio" name="group2" value="1" /> 있음 
<input type="radio" name="group2" value="2" /> 없음

<h3>학점비율</h3>
<input type="radio" name="group3" value="1" /> 잘줌 
<input type="radio" name="group3" value="2" /> 깐깐함
<input type="radio" name="group3" value="3" /> F주의

<h3>출결</h3>
<input type="radio" name="group4" value="1" />호명
<input type="radio" name="group4" value="2" /> 전자출결
<input type="radio" name="group4" value="3" /> 안함

<h3>시험횟수</h3>
<input type="radio" name="group5" value="1" />3번이상
<input type="radio" name="group5" value="2" /> 두번
<input type="radio" name="group5" value="3" /> 한번
<input type="radio" name="group5" value="4" /> 없음

</div>

<div class = "line"> </div>

<div class = "good">
    <h3>추천</h3>
    
    
    <pre><img class="like" src="{% static 'img/like.jpg'%}" width="40px" >     <img class="unlike" src="{% static 'img/unlike.jpg'%}" width="40px"></pre>


</div>

<div class = "line"> </div>

<div class = "year">
<label for="year">수강학기</label>
<br>
<br>
<select id="year">
<option value="20192">2019-2학기</option>
<option value="20191">2019-1학기</option>
<option value="20182">2018-2학기</option>

</select>

</div>

<div class = "line"> </div>

<div class = "text">
    <pre>네모칸씨에스에스 한거 안에 글자제한 500자로 텍스트 작성하게하기</pre>
</div>


        <input type = "submit" value = "제출하기" />
    </form>
</div>
</div>
{%endblock%}