mainproject/mainproject/urls.py
from django.contrib import admin
from django.urls import path, include

import mainapp.views
import account.views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',mainapp.views.home, name="home"),

    path('account/', include('account.urls')),
    path('write/', include ('write.urls')),
]

mainproject/user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'user'

urlpatterns = [
    path('join/', views.UserRegister.as_view(), name="join"),
    path('login/', views.UserLogin.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

mainproject/user/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from . validators import RegisteredEmailValidator


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model() # 프로젝트 폴더의 settings.py의 AUTH_USER_MODEL이 참조하는 모델을 찾아주는 함수
        fields = ['username']
        # 정의된 모델에서 폼에 보여줄 필드를 정의, password는 UserCreationForm에서 자동 생성

mainproject/user/views.py
from django.shortcuts import render
from django.views.generic import CreateView, FormView
from user.forms import UserRegisterForm
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView
from django.contrib import messages
from django.contrib.auth.tokens import default_token_generator
from django.views.generic.base import TemplateView
from django.shortcuts import redirect


# 회원가입
class UserRegister(CreateView):
    model = get_user_model()
    form_class = UserRegisterForm
    template_name = 'user/join.html'
    success_url = '/user/login/'


# 로그인
class UserLogin(LoginView):
    template_name = 'user/login.html'

    # 유효성 검증에 실패한 경우 form_invalid 메소드를 오버라이딩해서 에러 메시지를 출력
    def form_invalid(self, form):
        messages.error(self.request, 'ㅅㅂ', extra_tags='danger')
        return super().form_invalid(form)

mainproject/user/templates/join.html
{% extends 'base.html' %}
{% block content %}
<div class="title" style="background-color: black">회원가입</div>
    <div class="body" style="background-color:pink">
    <form method="post" action="{% url 'user:join' %}">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group" style="background-color: rgba(245, 245, 245, 0);">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        <input type="{{ field.field.widget.input_type }}"
            class="form-control {% if field.errors|length > 0 %}is-invalid{% endif %}"
            id="{{ field.id_for_label }}" name="{{ field.html_name }}"
            value="{{ field.value|default_if_none:'' }}"
            style="background-color: rgba(245, 245, 245, 0);">
        {% for error in field.errors %}
        <div class="invalid-feedback">{{ error }}</div>
        {% endfor %}
    </div>
    {% endfor %}
    <button type="submit" class="btn" style="background-color: rgba(245, 245, 245, 0);">가입</button>
    </form>
    </div>
    </div>
    </div>
    </div>
    </div>
{% endblock %}

mainproject/user/templates/login.html
{% extends 'base.html' %}
{% block content %}
  <div class="title" style="background-color: rgba(245, 245, 245, 0);">로그인</div>

    {% for message in messages %}
    <div class="form-group">
        <p>{{ message.message }}</p>
    </div>
    {% endfor %}
    <form method="post" action="{% url 'user:login' %}">
        {% csrf_token %}
        {% for field in form %}

        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            <input type="{{ field.field.widget.input_type }}"
                class="form-control {% if field.errors|length > 0 %}is-invalid{% endif %}"
                id="{{ field.id_for_label }}" name="{{ field.html_name }}"
                value="{{ field.value|default_if_none:'' }}"
                style="background-color: rgba(245, 245, 245, 0);">
            {% for error in field.errors %}
            <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        {% endfor %}
        <button type="submit" class="btn"
            style="background-color: rgba(245, 245, 245, 0);"> 로그인</button>
    </form>
  </div>
      </div>
  </div>
</div>
</div>
{% endblock %}